"""Add users and link tracks

Revision ID: a1e2f5f51453
Revises: de84ed66e4b3
Create Date: 2025-12-02 22:33:08.857348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # <--- Add this line right here


# revision identifiers, used by Alembic.
revision: str = 'a1e2f5f51453'
down_revision: Union[str, Sequence[str], None] = 'de84ed66e4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opentracks_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='NOW()', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opentracks_users_id'), 'opentracks_users', ['id'], unique=False)
    op.create_index(op.f('ix_opentracks_users_username'), 'opentracks_users', ['username'], unique=True)
    op.drop_index(op.f('idx_opentracks_track_points_geom_point'), table_name='opentracks_track_points', postgresql_using='gist')
    op.add_column('opentracks_tracks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_opentracks_tracks_geom_track'), table_name='opentracks_tracks', postgresql_using='gist')
    op.create_foreign_key(None, 'opentracks_tracks', 'opentracks_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opentracks_tracks', type_='foreignkey')
    op.create_index(op.f('idx_opentracks_tracks_geom_track'), 'opentracks_tracks', ['geom_track'], unique=False, postgresql_using='gist')
    op.drop_column('opentracks_tracks', 'user_id')
    op.create_index(op.f('idx_opentracks_track_points_geom_point'), 'opentracks_track_points', ['geom_point'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_opentracks_users_username'), table_name='opentracks_users')
    op.drop_index(op.f('ix_opentracks_users_id'), table_name='opentracks_users')
    op.drop_table('opentracks_users')
    # ### end Alembic commands ###
