"""add api key hash

Revision ID: aac28b052b11
Revises: a1e2f5f51453
Create Date: 2025-12-02 23:40:21.473889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # <--- Add this line right here


# revision identifiers, used by Alembic.
revision: str = 'aac28b052b11'
down_revision: Union[str, Sequence[str], None] = 'a1e2f5f51453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opentracks_users', sa.Column('api_key_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_opentracks_users_api_key_hash'), 'opentracks_users', ['api_key_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opentracks_users_api_key_hash'), table_name='opentracks_users')
    op.drop_column('opentracks_users', 'api_key_hash')
    # ### end Alembic commands ###
